import { CoffeeBean, BrewRecipe, BrewMethod, ProcessType, RoastLevel } from './types';

export const METHODS: BrewMethod[] = ['V60', 'Origami', 'Kalita Wave', 'Aeropress', 'Prensa Francesa', 'Espresso', 'Chemex', 'Switch', 'Otro'];
export const ROAST_LEVELS: RoastLevel[] = ['Claro', 'Medio', 'Medio-Oscuro', 'Oscuro'];
export const PROCESSES: ProcessType[] = ['Lavado', 'Natural', 'Honey', 'Experimental', 'Anaeróbico', 'Maceración Carbónica'];

export const EMPTY_BEAN: CoffeeBean = {
  id: '',
  name: '',
  roaster: '',
  origin: '',
  process: 'Lavado',
  roastDate: '',
  roastLevel: 'Claro',
  isArchived: false,
  recipes: []
};

export const EMPTY_RECIPE: BrewRecipe = {
  id: '',
  date: new Date().toISOString(),
  config: {
    method: 'V60',
    dripper: '',
    filterType: 'Papel',
    grinderModel: '',
    grinderSetting: '',
    dose: 15,
    waterAmount: 240,
    temperature: 93,
    totalTime: '02:30',
  },
  technique: {
    bloomWater: 45,
    bloomTime: 30,
    pours: 2,
    notes: '',
  },
  result: {
    aroma: 5,
    acidity: 5,
    sweetness: 5,
    bitterness: 5,
    body: 5,
    balance: 5,
    clarity: 5,
    aftertaste: 5,
    flavorNotes: '',
    overallScore: 5,
    generalFeeling: '',
  },
  learning: {
    diagnosis: 'Balanceado',
    changesForNextTime: '',
    changesFromPrevious: '',
  }
};

// --- Internationalization ---

export const LABELS = {
  roast: {
    'Claro': { es: 'Claro', en: 'Light' },
    'Medio': { es: 'Medio', en: 'Medium' },
    'Medio-Oscuro': { es: 'Medio-Oscuro', en: 'Medium-Dark' },
    'Oscuro': { es: 'Oscuro', en: 'Dark' },
  },
  process: {
    'Lavado': { es: 'Lavado', en: 'Washed' },
    'Natural': { es: 'Natural', en: 'Natural' },
    'Honey': { es: 'Honey', en: 'Honey' },
    'Experimental': { es: 'Experimental', en: 'Experimental' },
    'Anaeróbico': { es: 'Anaeróbico', en: 'Anaerobic' },
    'Maceración Carbónica': { es: 'Maceración Carbónica', en: 'Carbonic Maceration' },
  },
  method: {
    'Prensa Francesa': { es: 'Prensa Francesa', en: 'French Press' },
    'Otro': { es: 'Otro', en: 'Other' },
    // Standard names like V60 don't need translation usually, but can be added here
  },
  diagnosis: {
    'Sub-extraído': { es: 'Sub-extraído', en: 'Under-extracted' },
    'Balanceado': { es: 'Balanceado', en: 'Balanced' },
    'Sobre-extraído': { es: 'Sobre-extraído', en: 'Over-extracted' },
    'Excelente': { es: 'Excelente', en: 'Excellent' },
  }
};

export const TRANSLATIONS = {
  es: {
    appTitle: 'BaristaLog',
    myCoffees: 'Mis Cafés',
    manageStock: 'Gestiona tu stock y calibra tus recetas.',
    addCoffee: 'Agregar Café',
    noCoffees: 'Aún no tienes cafés',
    addFirst: 'Agrega tu primera bolsa de café para comenzar.',
    recipe: 'Receta',
    recipes: 'Recetas',
    last: 'Última',
    editCoffee: 'Editar Café',
    newCoffee: 'Nuevo Café',
    coffeeName: 'Nombre del Café',
    roaster: 'Tostador',
    countryRegion: 'País y Región',
    farmProducer: 'Finca / Productor',
    altitude: 'Altitud (msnm)',
    variety: 'Variedad',
    process: 'Proceso',
    roastDate: 'Fecha Tueste',
    openDate: 'Fecha Apertura',
    roastLevel: 'Nivel de Tueste',
    cancel: 'Cancelar',
    save: 'Guardar',
    back: 'Mis Cafés',
    score: 'Puntaje',
    logbook: 'Bitácora',
    newRecipe: 'Nueva Receta',
    noRecipes: 'Aún no hay recetas. ¡Prepara tu primera taza!',
    grind: 'Molienda',
    next: 'Siguiente',
    editRecipe: 'Editar Receta',
    preparation: 'Preparación',
    method: 'Método',
    device: 'Dripper / Dispositivo',
    dose: 'Dosis (g)',
    water: 'Agua (ml)',
    ratioCalc: 'Ratio Calculado',
    temp: 'Temp. (°C)',
    technique: 'Técnica',
    bloomWater: 'Bloom Agua (ml)',
    bloomTime: 'Bloom Tiempo (s)',
    pours: 'Num. Vertidos',
    totalTime: 'Tiempo Total',
    sensory: 'Análisis Sensorial',
    aroma: 'Aroma',
    acidity: 'Acidez',
    sweetness: 'Dulzura',
    body: 'Cuerpo',
    bitterness: 'Amargor',
    clarity: 'Claridad',
    balance: 'Balance',
    aftertaste: 'Retrogusto',
    flavorNotes: 'Notas de Sabor',
    flavorPlaceholder: 'Cítrico, Chocolate, Jazmín...',
    generalFeeling: 'Sensación General',
    generalPlaceholder: 'Una taza placentera...',
    overallScore: 'Puntaje General',
    learning: 'Ajustes y Aprendizaje',
    diagnosis: 'Diagnóstico de Extracción',
    changesPrev: 'Cambios desde la anterior',
    changesPrevPlaceholder: 'Ej. Molienda más gruesa (2.2 -> 2.4)',
    changesNext: '¿Qué cambiar en la próxima?',
    changesNextPlaceholder: 'Ej. Subir temperatura para resaltar acidez...',
    confirmDelete: '¿Estás seguro de que quieres eliminar esta receta?',
    diagnosisGood: '¡Muy buen balance!',
    diagnosisGoodDesc: 'Tus puntajes sensoriales indican una taza bien extraída.',
    detected: 'Detectado',
    sugg_fine: 'Moler más fino (aumentar superficie de contacto).',
    sugg_tempUp: 'Subir la temperatura del agua.',
    sugg_moreWater: 'Usar más agua (aumentar ratio).',
    sugg_agitate: 'Agitar más durante el bloom.',
    sugg_coarse: 'Moler más grueso.',
    sugg_tempDown: 'Bajar la temperatura del agua.',
    sugg_lessWater: 'Usar menos agua (disminuir ratio).',
    sugg_gentle: 'Verter más suavemente para reducir turbulencia.',
    sugg_excellent: '¡Gran extracción! Intenta replicar la receta exactamente para confirmar consistencia.'
  },
  en: {
    appTitle: 'BaristaLog',
    myCoffees: 'My Coffees',
    manageStock: 'Manage your stock and dial in your brews.',
    addCoffee: 'Add Coffee',
    noCoffees: 'No coffees yet',
    addFirst: 'Add your first bag of coffee to get started.',
    recipe: 'Recipe',
    recipes: 'Recipes',
    last: 'Last',
    editCoffee: 'Edit Coffee',
    newCoffee: 'New Coffee',
    coffeeName: 'Coffee Name',
    roaster: 'Roaster',
    countryRegion: 'Country & Region',
    farmProducer: 'Farm / Producer',
    altitude: 'Altitude (masl)',
    variety: 'Variety',
    process: 'Process',
    roastDate: 'Roast Date',
    openDate: 'Open Date',
    roastLevel: 'Roast Level',
    cancel: 'Cancel',
    save: 'Save',
    back: 'My Coffees',
    score: 'Score',
    logbook: 'Logbook',
    newRecipe: 'New Recipe',
    noRecipes: 'No recipes yet. Brew your first cup!',
    grind: 'Grind',
    next: 'Next',
    editRecipe: 'Edit Recipe',
    preparation: 'Preparation',
    method: 'Method',
    device: 'Dripper / Device',
    dose: 'Dose (g)',
    water: 'Water (ml)',
    ratioCalc: 'Calculated Ratio',
    temp: 'Temp. (°C)',
    technique: 'Technique',
    bloomWater: 'Bloom Water (ml)',
    bloomTime: 'Bloom Time (s)',
    pours: 'Pour Count',
    totalTime: 'Total Time',
    sensory: 'Sensory Analysis',
    aroma: 'Aroma',
    acidity: 'Acidity',
    sweetness: 'Sweetness',
    body: 'Body',
    bitterness: 'Bitterness',
    clarity: 'Clarity',
    balance: 'Balance',
    aftertaste: 'Aftertaste',
    flavorNotes: 'Flavor Notes',
    flavorPlaceholder: 'Citrus, Chocolate, Jasmine...',
    generalFeeling: 'General Feeling',
    generalPlaceholder: 'A pleasant cup...',
    overallScore: 'Overall Score',
    learning: 'Adjustments & Learning',
    diagnosis: 'Extraction Diagnosis',
    changesPrev: 'Changes from previous',
    changesPrevPlaceholder: 'e.g. Coarser grind (2.2 -> 2.4)',
    changesNext: 'What to change next time?',
    changesNextPlaceholder: 'e.g. Higher temp to highlight acidity...',
    confirmDelete: 'Are you sure you want to delete this recipe?',
    diagnosisGood: 'Great Balance!',
    diagnosisGoodDesc: 'Your sensory scores indicate a well-extracted cup.',
    detected: 'Detected',
    sugg_fine: 'Grind finer (increase surface area).',
    sugg_tempUp: 'Increase water temperature.',
    sugg_moreWater: 'Use more water (increase ratio).',
    sugg_agitate: 'Agitate more during bloom.',
    sugg_coarse: 'Grind coarser.',
    sugg_tempDown: 'Decrease water temperature.',
    sugg_lessWater: 'Use less water (decrease ratio).',
    sugg_gentle: 'Pour more gently to reduce turbulence.',
    sugg_excellent: 'Great extraction! Try to replicate exactly to confirm consistency.'
  }
};